name: Package Application with Pyinstaller

on:
  push: 
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    
    - uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with: 
        path: .
    
    - uses: actions/upload-artifact@v2
      with:
        name:  Fallkapselserver.exe
        path: ./dist/windows
